// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNqSFTNb6P1yNSSdpDb-fyx8CR8EbM7HA',
    appId: '1:239205165274:web:ace7ccbc0c9051dd14dde3',
    messagingSenderId: '239205165274',
    projectId: 'cnstn-18d84',
    authDomain: 'cnstn-18d84.firebaseapp.com',
    databaseURL: 'https://cnstn-18d84-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cnstn-18d84.firebasestorage.app',
    measurementId: 'G-VVKJ1HKKV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs5OPGPHYTCWeHw2zpLVNuiNl1uidmCgU',
    appId: '1:239205165274:android:de415fec78bc03f914dde3',
    messagingSenderId: '239205165274',
    projectId: 'cnstn-18d84',
    databaseURL: 'https://cnstn-18d84-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cnstn-18d84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQeEfMkuyWlto8GeScMsJD0M73aibS2yg',
    appId: '1:239205165274:ios:d53a7a48d9be242e14dde3',
    messagingSenderId: '239205165274',
    projectId: 'cnstn-18d84',
    databaseURL: 'https://cnstn-18d84-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cnstn-18d84.firebasestorage.app',
    iosBundleId: 'com.example.cnstn2026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQeEfMkuyWlto8GeScMsJD0M73aibS2yg',
    appId: '1:239205165274:ios:d53a7a48d9be242e14dde3',
    messagingSenderId: '239205165274',
    projectId: 'cnstn-18d84',
    databaseURL: 'https://cnstn-18d84-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cnstn-18d84.firebasestorage.app',
    iosBundleId: 'com.example.cnstn2026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNqSFTNb6P1yNSSdpDb-fyx8CR8EbM7HA',
    appId: '1:239205165274:web:ad466a8cce618a7e14dde3',
    messagingSenderId: '239205165274',
    projectId: 'cnstn-18d84',
    authDomain: 'cnstn-18d84.firebaseapp.com',
    databaseURL: 'https://cnstn-18d84-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cnstn-18d84.firebasestorage.app',
    measurementId: 'G-ZMBZSV7LVP',
  );
}
